### ISSUE TITLE
Does the mini-controller project continue

### ISSUE THREAD

**Issue by fengjiannan2010** [wwwizzarrdry/mini-controller#1]
Hello, I am very interested in your project. Is there a version available?
Will it be updated in the future?

**Comment by wwwizzarrdry** [comment]
The PoC was cool, but it was a little wonky. I've since broken it into separate controllers for Sonos, Roon and Plex. I dropped the LastFM module because they updated their API a while back and blocked users from accessing their artwork.

It would be too difficult to merge these services back into a single app again. I'll see if I can find some motivation here in the next few weeks to make another run at the project.

One of the big disappointments was the lack of features being added to the Roon API. It had such strong potential when I started, but so many updates came and went with nothing being added to the API, so I just focused on the Plex controller instead since I could do everything I wanted there even without an official API.
